/* eslint-disable */
// @ts-nocheck — wrapper's tsconfig uses moduleResolution:'node' which can't
// read the modern exports map at COMPILE time. Runtime resolution via Node's
// exports-map require-condition works correctly.
/**
 * Public @sogni-ai/sogni-intelligence-client/workflows
 * surface — carved out of @sogni/creative-agent.
 *
 * Generated by scripts/generate-subpath-shims.mjs. Do not edit by hand.
 * Run `npm run sync:subpath-shims` to regenerate.
 *
 * Explicit named re-exports (not `export *`) so that downstream CJS
 * builds compile to statically analyzable named exports — required by
 * Vite/Rollup consumers (sogni-web, sogni-chat).
 */
export {
  BindingError,
  collectBindings,
  computeStaleStageIds,
  createRun,
  executeRun,
  getCurrentRunStage,
  getFlatWorkflowStages,
  isBinding,
  parseBinding,
  persistedArtifact,
  persistedArtifactItem,
  persistedRun,
  resolveBindings,
  summarizeWorkflowTemplate,
  validateWorkflow,
  walkStages,
} from '@sogni/creative-agent/workflows';

export type {
  Artifact,
  ArtifactItem,
  ArtifactKind,
  ArtifactVersion,
  BatchStage,
  BindingContext,
  ExecutorEvent,
  ExecutorOptions,
  FixedStage,
  InteractiveStage,
  ParsedBinding,
  PathSegment,
  ResumeInput,
  Run,
  RunState,
  RunStore,
  StageBase,
  StageCondition,
  StageExecution,
  StageExecutionState,
  StageItemState,
  SummarizeWorkflowTemplateOptions,
  ToolDispatcher,
  ToolExecutionProgress,
  ValidationIssue,
  ValidationResult,
  WorkflowAuthor,
  WorkflowCategory,
  WorkflowGraphLayout,
  WorkflowInput,
  WorkflowInputType,
  WorkflowPreviewArtifact,
  WorkflowStability,
  WorkflowStage,
  WorkflowTemplate,
  WorkflowVisibility,
} from '@sogni/creative-agent/workflows';
