export const CHARACTER_SHEET_DEFAULT_CANVAS = {
    width: 1536,
    height: 1024,
    aspectRatio: '1536x1024',
};
const CHARACTER_SHEET_MARKER = 'PROFESSIONAL CHARACTER SHEET CONTRACT';
function normalizeText(text) {
    return text.replace(/[“”]/g, '"').replace(/[’]/g, "'").replace(/\s+/g, ' ').trim();
}
export function textRequestsProfessionalCharacterSheetImage(text) {
    const normalized = normalizeText(text);
    if (!normalized)
        return false;
    const generationVerb = String.raw `(?:generate|create|make|render|produce|design|build|develop|draw)`;
    const characterSubject = String.raw `(?:character|mascot|brand\s+mascot|creature|avatar|persona|toon|cartoon\s+character)`;
    const sheetArtifact = String.raw `(?:character\s+sheet|mascot\s+sheet|model\s+sheet|reference\s+(?:sheet|board)|design\s+sheet|turnaround(?:\s+(?:sheet|views?|board))?|expression\s+(?:sheet|row|board)|pose\s+(?:sheet|board))`;
    const directCharacterSheet = new RegExp(String.raw `\b${characterSubject}\b[\s\S]{0,80}\b(?:sheet|reference\s+(?:sheet|board)|model\s+sheet|turnaround(?:\s+(?:sheet|views?|board))?|expression\s+(?:sheet|row|board)|pose\s+(?:sheet|board))\b`, 'i').test(normalized)
        || new RegExp(String.raw `\b${sheetArtifact}\b[\s\S]{0,80}\b${characterSubject}\b`, 'i').test(normalized)
        || /\breusable\s+character\s+sheet\b/i.test(normalized);
    if (!directCharacterSheet)
        return false;
    return new RegExp(String.raw `\b${generationVerb}\b[\s\S]{0,180}\b${sheetArtifact}\b`, 'i').test(normalized)
        || new RegExp(String.raw `\b${sheetArtifact}\b[\s\S]{0,120}\b(?:image|illustration|artwork|render|board|layout)\b`, 'i').test(normalized)
        || new RegExp(String.raw `\b(?:need|want|would\s+like|looking\s+for|please|can\s+you|could\s+you)\b[\s\S]{0,120}\b${sheetArtifact}\b`, 'i').test(normalized);
}
export function promptContainsProfessionalCharacterSheetInstruction(text) {
    return normalizeText(text).includes(CHARACTER_SHEET_MARKER);
}
export function prependProfessionalCharacterSheetInstruction(prompt, userIntentText = '') {
    const trimmedPrompt = prompt.trim();
    if (!trimmedPrompt)
        return trimmedPrompt;
    if (trimmedPrompt.includes(CHARACTER_SHEET_MARKER))
        return trimmedPrompt;
    const textCopyInstruction = /\b(?:slogan|tagline|logo|brand|copy|text|caption|label|headline|title|wording|reads?|says?)\b/i.test(userIntentText)
        ? 'Preserve exact user-provided brand names, slogans, taglines, logo text, labels, and requested copy verbatim; incidental tiny notes such as personality or fun-fact blurbs may be generated by the image model when the user did not provide exact wording.'
        : 'Use clean, readable typography for labels and notes; any incidental personality, fun-fact, or usage notes may be generated by the image model unless the user supplied exact copy.';
    return [
        `${CHARACTER_SHEET_MARKER}: Create one polished, reusable animation/brand mascot character design sheet, not a sparse six-panel grid and not separate image variations.`,
        'Keep the character identity consistent across every view and pose. Use uploaded reference images as assigned by the request; preserve logos and brand assets where used.',
        'Layout should feel like a professional character reference board on a soft neutral studio background with clean typography and an organized product-brand design aesthetic.',
        'Include, when visually feasible in the single sheet: a large hero pose; turnaround views labeled front, 3/4 front, side, back, and 3/4 back; an expression row; action/personality poses; accessory or prop callouts; color palette swatches; compact personality notes; fun facts or brand usage notes.',
        textCopyInstruction,
        'Prioritize high-quality 3D rendered or polished illustration detail, soft studio lighting, consistent proportions, expressive personality, and sharp presentation.',
        trimmedPrompt,
    ].join(' ');
}
//# sourceMappingURL=characterSheet.js.map