// Generated by scripts/generate-subpath-shims.mjs. Do not edit by hand.
// Static ESM re-export of @sogni/creative-agent's subpath. Vite/Rollup
// can follow this through to the source via @sogni/creative-agent's own
// ESM dist (which uses static `export *`). Types come from the .ts shim.
export {
  addAsset,
  createAssetManifest,
  findAsset,
  formatModelRef,
  getModelRefFormat,
  getModelRefFormatEntries,
  getModelRefFormatResolution,
  listAssets,
  listKnownAssetModelIds,
  mapAssetsForModel,
  updateAsset,
  validateAssetReferences,
} from '@sogni/creative-agent/skills/asset_reference_management';
