/**
 * Curated prompt seeds used when a user asks for generation without providing
 * a concrete idea. Keeping these central prevents apps from drifting into
 * different random-prompt behavior.
 *
 * Phase 8.5-prep moves this pure-data helper out of `src/prompts/` so the
 * PUBLIC bucket of the upcoming `@sogni-ai/sogni-intelligence-client`
 * carve-out can import it without crossing into PRIVATE prompt-composition
 * internals. `src/prompts/randomThemes.ts` re-exports the symbols here for
 * back-compat with existing private consumers.
 */
export const RANDOM_THEMES = [
  'a mountain summit',
  'a bamboo forest',
  'a frozen waterfall',
  'a lavender field',
  'a volcanic coastline',
  'a bay at night',
  'a salt flat with cracked earth',
  'a redwood forest',
  'a coral reef with sea life',
  'a rolling prairie',
  'a narrow alley in the rain',
  'an old movie theater',
  'a busy outdoor market',
  'a concrete overpass',
  'a rooftop garden above a city',
  'a canal with boats',
  'a glass skyscraper',
  'a subway station',
  'a cobblestone square',
  'an open-air night market',
  'a bookshop with tall shelves',
  'an arcade with game machines',
  'a cathedral interior',
  'a cabin interior during a storm',
  'an artist studio with paint everywhere',
  'an abandoned hallway',
  'a spaceship control room',
  'a greenhouse full of plants',
  'a small music club with a stage',
  'a pottery workshop',
  'a street musician playing violin',
  'a fisherman mending nets',
  'a dancer practicing alone',
  'a blacksmith forging metal',
  'a child chasing fireflies',
  'a surfer riding a wave',
  'a chef preparing food in a kitchen',
  'a climber resting on a ridge',
  'a painter working on a mural',
  'a person walking through a temple garden',
  'a wolf pack crossing a river',
  'a hummingbird near flowers',
  'an octopus moving through a shipwreck',
  'wild horses galloping on a beach',
  'a leopard on a cliff edge',
  'an owl swooping through a forest',
  'jellyfish drifting in deep water',
  'a fox on a forest floor',
  'a whale breaching the surface',
  'flamingos on a lake',
  'a city floating above clouds',
  'a street vendor selling unusual wares',
  'a dragon on a tower',
  'an explorer in an alien jungle',
  'a knight crossing a stone bridge',
  'a person stepping out of a portal',
  'a robot tending a garden',
  'a potion brewer in a tower',
  'a warrior standing in a flower field',
  'a domed city underwater',
  'a locomotive crossing a bridge',
  'a sailboat on the open ocean',
  'a motorcycle on a coastal road',
  'a hot air balloon over a valley',
  'a truck on a desert road',
  'a fishing boat in rough seas',
  'a bicycle leaning against a wall',
  'a cable car over a gorge',
  'a canoe on a still lake',
  'a spaceship landing on a planet',
  'a lightning storm over a field',
  'a rainbow over a waterfall',
  'a sandstorm approaching an oasis',
  'an aurora over a tundra',
  'fog rolling through a harbor',
  'a downpour flooding a street',
  'snowfall covering a village',
  'heat shimmer over a highway',
  'a wildfire on a ridge',
  'rain falling on a garden',
  'a table set for a feast outdoors',
  'a bowl of soup in a small shop',
  'a market stall with tropical fruits',
  'a pastry display in a bakery',
  'a campfire under the stars',
  'ink dissolving in water',
  'glass fragments mid-explosion',
  'paint splashing on a canvas',
  'smoke forming spirals',
  'leaves caught in wind',
] as const;

export const RANDOM_LYRICS_THEMES = [
  'missing someone far away',
  'falling for a stranger',
  'letting go of the past',
  'a love that came too late',
  'growing apart from a friend',
  'forgiving someone who hurt you',
  'the moment before a first kiss',
  'a letter you never sent',
  'dancing alone in your room',
  'waiting for a phone call',
  'finding yourself after losing everything',
  'pretending to be fine',
  'the person you used to be',
  'learning to trust yourself',
  'the mask you wear for others',
  'outgrowing your hometown',
  'starting over in a new place',
  'the voice inside your head',
  'becoming someone unexpected',
  'celebrating your own flaws',
  'a road trip with no destination',
  'the last day of summer',
  'a conversation at 3am',
  'running away from responsibility',
  'a promise made in the rain',
  'sneaking out at midnight',
  'a goodbye at a train station',
  'waking up in an unfamiliar place',
  'a party that changed everything',
  'chasing a dream everyone doubts',
  'the ocean at night',
  'walking through an empty city',
  'a fire burning low',
  'stars seen from a rooftop',
  'a storm rolling in',
  'footprints in fresh snow',
  'a river that keeps flowing',
  'the silence after thunder',
  'a garden growing wild',
  'the horizon at sunrise',
  'time moving too fast',
  'the weight of unspoken words',
  'chasing shadows',
  'a door that only opens once',
  'the space between heartbeats',
  'colors you cannot name',
  'echoes of a forgotten song',
  'building something from nothing',
  'the price of freedom',
  'a world inside a dream',
] as const;

function pickRandom<T>(items: readonly T[], random: () => number): T {
  return items[Math.floor(random() * items.length)];
}

export function getRandomTheme(random: () => number = Math.random): string {
  return pickRandom(RANDOM_THEMES, random);
}

export function getRandomLyricsTheme(random: () => number = Math.random): string {
  return pickRandom(RANDOM_LYRICS_THEMES, random);
}
