/* eslint-disable */
// @ts-nocheck — wrapper's tsconfig uses moduleResolution:'node' which can't
// read the modern exports map at COMPILE time. Runtime resolution via Node's
// exports-map require-condition works correctly.
/**
 * Public @sogni-ai/sogni-intelligence-client/replay
 * surface — carved out of @sogni/creative-agent.
 *
 * Generated by scripts/generate-subpath-shims.mjs. Do not edit by hand.
 * Run `npm run sync:subpath-shims` to regenerate.
 *
 * Explicit named re-exports (not `export *`) so that downstream CJS
 * builds compile to statically analyzable named exports — required by
 * Vite/Rollup consumers (sogni-web, sogni-chat).
 */
export {
  REDACTION_PLACEHOLDER,
  RUN_RECORD_SCHEMA_VERSION,
  emptyRunRecord,
  redactPayload,
  redactRunRecord,
  redactStringValue,
} from '@sogni/creative-agent/replay';

export type {
  RunRecord,
  RunRecordAuditResult,
  RunRecordCostBreakdown,
  RunRecordRound,
  RunRecordToolCall,
  RunRecordToolResult,
} from '@sogni/creative-agent/replay';
